// Copyright 2026 the V8 project authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#include "src/compiler/turboshaft/wasm-bounds-check-elimination-reducer.h"

#include "src/compiler/turboshaft/assembler.h"
#include "src/compiler/turboshaft/copying-phase.h"
#include "src/compiler/turboshaft/operations.h"
#include "src/compiler/turboshaft/representations.h"
#include "src/flags/flags.h"
#include "test/common/flag-utils.h"
#include "test/unittests/compiler/turboshaft/reducer-test.h"

namespace v8::internal::compiler::turboshaft {

#include "src/compiler/turboshaft/define-assembler-macros.inc"

class WasmBoundsCheckEliminationReducerTest : public ReducerTest {
 public:
  WasmBoundsCheckEliminationReducerTest()
      : flag_bounds_check_elimination_(
            &v8_flags.turboshaft_wasm_bounds_check_elimination, true) {}

  // The graph built by {builder} gets two arrays {a} and {b}, an index
  // {i} and a condition {c} as parameters.
  template <typename Builder>
  TestInstance CreateTest(const Builder& builder) {
    std::initializer_list<RegisterRepresentation> parameter_reps{
        RegisterRepresentation::Tagged(), RegisterRepresentation::Tagged(),
        RegisterRepresentation::Word32(), RegisterRepresentation::Word32()};
    return CreateFromGraph(
        base::VectorOf(parameter_reps),
        [&builder](auto& Asm) {
          builder(Asm, V<WasmArrayNullable>::Cast(Asm.GetParameter(0)),
                  V<WasmArrayNullable>::Cast(Asm.GetParameter(1)),
                  Asm.template GetParameter<Word32>(2),
                  Asm.template GetParameter<Word32>(3));
          __ Return(__ Word32Constant(0));
        },
        true);
  }

  // Emits the bounds check for {array[index + offset]} the way the
  // graph builder does. No index means a constant index.
  template <typename Asm_t>
  static void BoundsCheck(Asm_t& Asm, V<WasmArrayNullable> array,
                          OptionalV<Word32> index, int32_t offset) {
    V<Word32> length = __ ArrayLength(array, compiler::kWithNullCheck);
    V<Word32> full_index = __ Word32Constant(offset);
    if (index.has_value()) {
      full_index =
          offset == 0 ? index.value() : __ Word32Add(index.value(), full_index);
    }
    __ TrapIfNot(__ Uint32LessThan(full_index, length),
                 TrapId::kTrapArrayOutOfBounds);
  }

  // Emits a branch on {condition}, and the code generated by {body} in
  // the true branch.
  template <typename Asm_t, typename Body>
  static void If(Asm_t& Asm, V<Word32> condition, const Body& body) {
    Block* if_true = __ NewBlock();
    Block* if_false = __ NewBlock();
    Block* merge = __ NewBlock();
    __ Branch(condition, if_true, if_false);
    __ Bind(if_true);
    body();
    __ Goto(merge);
    __ Bind(if_false);
    __ Goto(merge);
    __ Bind(merge);
  }

  // Emits a branch to an unreachable block when {condition} holds, and
  // continues otherwise. This is how wasm_of_ocaml raises an exception
  // for an OCaml bounds check.
  template <typename Asm_t>
  static void FailIf(Asm_t& Asm, V<Word32> condition) {
    Block* failure = __ NewBlock();
    Block* success = __ NewBlock();
    __ Branch(condition, failure, success);
    __ Bind(failure);
    __ Unreachable();
    __ Bind(success);
  }

  // {a.length - reduction}.
  template <typename Asm_t>
  static V<Word32> ReducedLength(Asm_t& Asm, V<WasmArrayNullable> array,
                                 int32_t reduction) {
    return __ Word32Sub(__ ArrayLength(array, compiler::kWithNullCheck),
                        __ Word32Constant(reduction));
  }

  static void Run(TestInstance& test) {
    test.Run<WasmBoundsCheckEliminationReducer>();
  }

 private:
  const FlagScope<bool> flag_bounds_check_elimination_;
};

TEST_F(WasmBoundsCheckEliminationReducerTest, RedundantConstantIndex) {
  // a[1]; a[0];
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    BoundsCheck(Asm, a, {}, 1);
    BoundsCheck(Asm, a, {}, 0);
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 1u);
  ASSERT_EQ(test.CountOp(Opcode::kUnreachable), 0u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, RedundantBetweenChecks) {
  // a[i]; a[i+2]; a[i+1];
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    BoundsCheck(Asm, a, i, 0);
    BoundsCheck(Asm, a, i, 2);
    BoundsCheck(Asm, a, i, 1);
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 2u);
  ASSERT_EQ(test.CountOp(Opcode::kUnreachable), 0u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, ConstantIndexOneSidedGuard) {
  // a[0]; a[1]; a[2]; -> guarded by 2 < a.length
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    BoundsCheck(Asm, a, {}, 0);
    BoundsCheck(Asm, a, {}, 1);
    BoundsCheck(Asm, a, {}, 2);
  });
  Run(test);
  // The traps are only in the fallback code.
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 3u);
  ASSERT_EQ(test.CountOp(Opcode::kUnreachable), 1u);
  // 3 original comparisons, 1 guard, 3 in the fallback code.
  ASSERT_EQ(test.CountOp(Opcode::kComparison), 7u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, NoFallbackForSingleCheck) {
  // a[0]; a[1]; could be guarded by 1 < a.length, but this only
  // eliminates one bounds check.
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    BoundsCheck(Asm, a, {}, 0);
    BoundsCheck(Asm, a, {}, 1);
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 2u);
  ASSERT_EQ(test.CountOp(Opcode::kUnreachable), 0u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, NoFallbackForTwoSidedGuard) {
  // a[i]; a[i+1]; would need a guard with two checks.
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    BoundsCheck(Asm, a, i, 0);
    BoundsCheck(Asm, a, i, 1);
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 2u);
  ASSERT_EQ(test.CountOp(Opcode::kUnreachable), 0u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, NoFallbackForTwoSidedGuardBelow) {
  // a[i+1]; a[i]; would need a guard with two checks.
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    BoundsCheck(Asm, a, i, 1);
    BoundsCheck(Asm, a, i, 0);
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 2u);
  ASSERT_EQ(test.CountOp(Opcode::kUnreachable), 0u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, TwoSidedGuardForFourChecks) {
  // a[i]; a[i+1]; a[i+2]; a[i+3];
  // -> guarded by i < a.length && i+3 < a.length
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    BoundsCheck(Asm, a, i, 0);
    BoundsCheck(Asm, a, i, 1);
    BoundsCheck(Asm, a, i, 2);
    BoundsCheck(Asm, a, i, 3);
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 4u);
  ASSERT_EQ(test.CountOp(Opcode::kUnreachable), 1u);
  // 4 original comparisons, 2 guards, 4 in the fallback code.
  ASSERT_EQ(test.CountOp(Opcode::kComparison), 10u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, TwoSidedGuardForChainBelow) {
  // a[i+7]; a[i+5]; a[i+3]; a[i+1];
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    BoundsCheck(Asm, a, i, 7);
    BoundsCheck(Asm, a, i, 5);
    BoundsCheck(Asm, a, i, 3);
    BoundsCheck(Asm, a, i, 1);
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 4u);
  ASSERT_EQ(test.CountOp(Opcode::kUnreachable), 1u);
  ASSERT_EQ(test.CountOp(Opcode::kComparison), 10u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest,
       NonNegativeIndexMakesCheckRedundant) {
  // a[i]; b[i+1]; b[i];
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    BoundsCheck(Asm, a, i, 0);
    BoundsCheck(Asm, b, i, 1);
    BoundsCheck(Asm, b, i, 0);
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 2u);
  ASSERT_EQ(test.CountOp(Opcode::kUnreachable), 0u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, NonNegativeIndexLearntLater) {
  // b[i+5]; a[i]; b[i+1];
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    BoundsCheck(Asm, b, i, 5);
    BoundsCheck(Asm, a, i, 0);
    BoundsCheck(Asm, b, i, 1);
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 2u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest,
       NonNegativeIndexDoesNotCoverSmallerOffsets) {
  // a[i+2]; b[i+1]; b[i];
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    BoundsCheck(Asm, a, i, 2);
    BoundsCheck(Asm, b, i, 1);
    BoundsCheck(Asm, b, i, 0);
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 3u);
  ASSERT_EQ(test.CountOp(Opcode::kUnreachable), 0u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, NonNegativeIndexOneSidedGuard) {
  // a[i]; b[i]; b[i+1]; b[i+2]; -> guarded by i+2 < b.length
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    BoundsCheck(Asm, a, i, 0);
    BoundsCheck(Asm, b, i, 0);
    BoundsCheck(Asm, b, i, 1);
    BoundsCheck(Asm, b, i, 2);
  });
  Run(test);
  // The first trap, and the other three in the fallback code.
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 4u);
  ASSERT_EQ(test.CountOp(Opcode::kUnreachable), 1u);
  // 4 original comparisons, 1 guard, 3 in the fallback code.
  ASSERT_EQ(test.CountOp(Opcode::kComparison), 8u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest,
       NonNegativeIndexFromSignedComparison) {
  // if (i >= 0) { a[i+1]; a[i]; }
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    If(Asm, __ Int32LessThanOrEqual(__ Word32Constant(0), i), [&]() {
      BoundsCheck(Asm, a, i, 1);
      BoundsCheck(Asm, a, i, 0);
    });
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 1u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest,
       NonNegativeIndexFromUnsignedComparison) {
  // if (i < 100) { a[i+1]; a[i]; }
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    If(Asm, __ Uint32LessThan(i, __ Word32Constant(100)), [&]() {
      BoundsCheck(Asm, a, i, 1);
      BoundsCheck(Asm, a, i, 0);
    });
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 1u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest,
       NoNonNegativeIndexFromLargeBound) {
  // if (i < 0x80000001) { a[i+1]; a[i]; }
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    If(Asm, __ Uint32LessThan(i, __ Word32Constant(0x80000001)), [&]() {
      BoundsCheck(Asm, a, i, 1);
      BoundsCheck(Asm, a, i, 0);
    });
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 2u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, NoFactsFromNonDominatingBranch) {
  // if (c) { a[i]; } a[i];
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    If(Asm, c, [&]() { BoundsCheck(Asm, a, i, 0); });
    BoundsCheck(Asm, a, i, 0);
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 2u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, FactsFromDominatingBranch) {
  // if (i < a.length) { a[i]; }
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    V<Word32> length = __ ArrayLength(a, compiler::kWithNullCheck);
    If(Asm, __ Uint32LessThan(i, length), [&]() { BoundsCheck(Asm, a, i, 0); });
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 0u);
}

// b[i] shows that i is non-negative. Then a[i+5]; a[i+6]; a[i+7] and
// a[i-1]; a[i-2]; a[i-3] give two fallback sequences with a one-sided
// guard each. The condition of a[i-1] is computed right after the trap
// of a[i+7] when {gap} is false, and one instruction later otherwise.
template <typename Asm_t>
static void TwoSequences(Asm_t& Asm, V<WasmArrayNullable> a,
                         V<WasmArrayNullable> b, V<Word32> i, bool gap) {
  using Test = WasmBoundsCheckEliminationReducerTest;
  Test::BoundsCheck(Asm, b, i, 0);
  Test::BoundsCheck(Asm, a, i, 5);
  Test::BoundsCheck(Asm, a, i, 6);
  V<Word32> length = __ ArrayLength(a, compiler::kWithNullCheck);
  V<Word32> index = __ Word32Add(i, __ Word32Constant(-1));
  Test::BoundsCheck(Asm, a, i, 7);
  if (gap) __ Word32Add(i, __ Word32Constant(42));
  __ TrapIfNot(__ Uint32LessThan(index, length), TrapId::kTrapArrayOutOfBounds);
  Test::BoundsCheck(Asm, a, i, -2);
  Test::BoundsCheck(Asm, a, i, -3);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, CoalesceTouchingSequences) {
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    TwoSequences(Asm, a, b, i, /*gap*/ false);
  });
  Run(test);
  // A single fallback sequence, with a two-sided guard, covers the
  // six bounds checks of {a}.
  ASSERT_EQ(test.CountOp(Opcode::kUnreachable), 1u);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 7u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, NoCoalescingAcrossGap) {
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    TwoSequences(Asm, a, b, i, /*gap*/ true);
  });
  Run(test);
  // The two sequences do not overlap, so they are kept separate.
  ASSERT_EQ(test.CountOp(Opcode::kUnreachable), 2u);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 7u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, FallbackSequenceStartingAtTrap) {
  // a[i]; b[i]; b[i+1]; b[i+2]; where the condition of the check of b[i]
  // is not right before its trap, so the fallback code starts at the
  // trap.
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    BoundsCheck(Asm, a, i, 0);
    V<Word32> length = __ ArrayLength(b, compiler::kWithNullCheck);
    V<Word32> condition = __ Uint32LessThan(i, length);
    __ Word32Add(i, __ Word32Constant(42));
    __ TrapIfNot(condition, TrapId::kTrapArrayOutOfBounds);
    BoundsCheck(Asm, b, i, 1);
    BoundsCheck(Asm, b, i, 2);
  });
  Run(test);
  // The first trap, and the other three in the fallback code.
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 4u);
  ASSERT_EQ(test.CountOp(Opcode::kUnreachable), 1u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, OCamlBoundsCheck) {
  // a[0]; if (a.length - 1 <= i) fail; a[i+1];
  // The first access shows that the length is at least 1, so the OCaml
  // bounds check shows that a[i+1] is within bounds.
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    BoundsCheck(Asm, a, {}, 0);
    FailIf(Asm, __ Uint32LessThanOrEqual(ReducedLength(Asm, a, 1), i));
    BoundsCheck(Asm, a, i, 1);
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 1u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, OCamlBoundsCheckAsAddition) {
  // a[0]; if (a.length + (-1) <= i) fail; a[i+1];
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    BoundsCheck(Asm, a, {}, 0);
    V<Word32> length = __ ArrayLength(a, compiler::kWithNullCheck);
    FailIf(Asm, __ Uint32LessThanOrEqual(
                    __ Word32Add(length, __ Word32Constant(-1)), i));
    BoundsCheck(Asm, a, i, 1);
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 1u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, OCamlBoundsCheckUnknownLength) {
  // if (a.length - 1 <= i) fail; a[i+1];
  // The array might be empty, in which case a.length - 1 wraps around
  // and the OCaml bounds check does not show anything.
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    FailIf(Asm, __ Uint32LessThanOrEqual(ReducedLength(Asm, a, 1), i));
    BoundsCheck(Asm, a, i, 1);
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 1u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, OCamlBoundsChecksInSequence) {
  // a[i+1] after the OCaml bounds check of a.(i) shows that the length is
  // at least 1, so the Wasm bounds checks of a.(j) and a.(k) are
  // redundant.
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    FailIf(Asm, __ Uint32LessThanOrEqual(ReducedLength(Asm, a, 1), i));
    BoundsCheck(Asm, a, i, 1);
    FailIf(Asm, __ Uint32LessThanOrEqual(ReducedLength(Asm, a, 1), c));
    BoundsCheck(Asm, a, c, 1);
    V<Word32> k = __ Word32Add(i, c);
    FailIf(Asm, __ Uint32LessThanOrEqual(ReducedLength(Asm, a, 1), k));
    BoundsCheck(Asm, a, k, 1);
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 1u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, ReducedLengthCoversRange) {
  // a[1]; if (i < a.length - 2) { a[i]; a[i+1]; a[i+2]; }
  // a[1] shows that the length is at least 2.
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    BoundsCheck(Asm, a, {}, 1);
    If(Asm, __ Uint32LessThan(i, ReducedLength(Asm, a, 2)), [&]() {
      BoundsCheck(Asm, a, i, 0);
      BoundsCheck(Asm, a, i, 1);
      BoundsCheck(Asm, a, i, 2);
    });
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 1u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, ReducedLengthTooLarge) {
  // a[0]; if (i < a.length - 2) { a[i+2]; }
  // a[0] only shows that the length is at least 1, so a.length - 2 may
  // wrap around.
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    BoundsCheck(Asm, a, {}, 0);
    If(Asm, __ Uint32LessThan(i, ReducedLength(Asm, a, 2)),
       [&]() { BoundsCheck(Asm, a, i, 2); });
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 2u);
}

#include "src/compiler/turboshaft/undef-assembler-macros.inc"

}  // namespace v8::internal::compiler::turboshaft
