// Copyright 2026 the V8 project authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#include "src/compiler/turboshaft/wasm-bounds-check-elimination-reducer.h"

#include "src/compiler/turboshaft/assembler.h"
#include "src/compiler/turboshaft/copying-phase.h"
#include "src/compiler/turboshaft/operations.h"
#include "src/compiler/turboshaft/representations.h"
#include "src/flags/flags.h"
#include "test/common/flag-utils.h"
#include "test/unittests/compiler/turboshaft/reducer-test.h"

namespace v8::internal::compiler::turboshaft {

#include "src/compiler/turboshaft/define-assembler-macros.inc"

class WasmBoundsCheckEliminationReducerTest : public ReducerTest {
 public:
  WasmBoundsCheckEliminationReducerTest()
      : flag_bounds_check_elimination_(
            &v8_flags.turboshaft_wasm_bounds_check_elimination, true) {}

  // The graph built by {builder} gets two arrays {a} and {b}, an index
  // {i} and a condition {c} as parameters.
  template <typename Builder>
  TestInstance CreateTest(const Builder& builder) {
    std::initializer_list<RegisterRepresentation> parameter_reps{
        RegisterRepresentation::Tagged(), RegisterRepresentation::Tagged(),
        RegisterRepresentation::Word32(), RegisterRepresentation::Word32()};
    return CreateFromGraph(
        base::VectorOf(parameter_reps),
        [&builder](auto& Asm) {
          builder(Asm, V<WasmArrayNullable>::Cast(Asm.GetParameter(0)),
                  V<WasmArrayNullable>::Cast(Asm.GetParameter(1)),
                  Asm.template GetParameter<Word32>(2),
                  Asm.template GetParameter<Word32>(3));
          __ Return(__ Word32Constant(0));
        },
        true);
  }

  // Emits the bounds check for {array[index + offset]} the way the
  // graph builder does. No index means a constant index.
  template <typename Asm_t>
  static void BoundsCheck(Asm_t& Asm, V<WasmArrayNullable> array,
                          OptionalV<Word32> index, int32_t offset) {
    V<Word32> length = __ ArrayLength(array, compiler::kWithNullCheck);
    V<Word32> full_index = __ Word32Constant(offset);
    if (index.has_value()) {
      full_index =
          offset == 0 ? index.value() : __ Word32Add(index.value(), full_index);
    }
    __ TrapIfNot(__ Uint32LessThan(full_index, length),
                 TrapId::kTrapArrayOutOfBounds);
  }

  // Emits a branch on {condition}, and the code generated by {body} in
  // the true branch.
  template <typename Asm_t, typename Body>
  static void If(Asm_t& Asm, V<Word32> condition, const Body& body) {
    Block* if_true = __ NewBlock();
    Block* if_false = __ NewBlock();
    Block* merge = __ NewBlock();
    __ Branch(condition, if_true, if_false);
    __ Bind(if_true);
    body();
    __ Goto(merge);
    __ Bind(if_false);
    __ Goto(merge);
    __ Bind(merge);
  }

  // Emits a branch to an unreachable block when {condition} holds, and
  // continues otherwise. This is how wasm_of_ocaml raises an exception
  // for an OCaml bounds check.
  template <typename Asm_t>
  static void FailIf(Asm_t& Asm, V<Word32> condition) {
    Block* failure = __ NewBlock();
    Block* success = __ NewBlock();
    __ Branch(condition, failure, success);
    __ Bind(failure);
    __ Unreachable();
    __ Bind(success);
  }

  // {a.length - reduction}.
  template <typename Asm_t>
  static V<Word32> ReducedLength(Asm_t& Asm, V<WasmArrayNullable> array,
                                 int32_t reduction) {
    return __ Word32Sub(__ ArrayLength(array, compiler::kWithNullCheck),
                        __ Word32Constant(reduction));
  }

  static void Run(TestInstance& test) {
    test.Run<WasmBoundsCheckEliminationReducer>();
  }

  // The number of comparisons of a guard checking both bounds.
  static constexpr size_t kTwoSidedGuardComparisons =
      FallbackInstructionSequence::single_comparison_two_sided_guard ? 1 : 2;

  // The number of 64-bit comparisons, as used by single-comparison
  // guards checking both bounds.
  static size_t CountWord64Comparisons(TestInstance& test) {
    size_t count = 0;
    for (const Operation& op : test.graph().AllOperations()) {
      const ComparisonOp* comparison = op.TryCast<ComparisonOp>();
      if (comparison && comparison->rep == RegisterRepresentation::Word64()) {
        count++;
      }
    }
    return count;
  }

 private:
  const FlagScope<bool> flag_bounds_check_elimination_;
};

TEST_F(WasmBoundsCheckEliminationReducerTest, RedundantConstantIndex) {
  // a[1]; a[0];
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    BoundsCheck(Asm, a, {}, 1);
    BoundsCheck(Asm, a, {}, 0);
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 1u);
  ASSERT_EQ(test.CountOp(Opcode::kUnreachable), 0u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, RedundantBetweenChecks) {
  // a[i]; a[i+2]; a[i+1];
  // On 64-bit targets, a[i]; a[i+2]; also get fallback code.
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    BoundsCheck(Asm, a, i, 0);
    BoundsCheck(Asm, a, i, 2);
    BoundsCheck(Asm, a, i, 1);
  });
  Run(test);
  bool fallback =
      FallbackInstructionSequence::single_comparison_two_sided_guard;
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 2u);
  ASSERT_EQ(test.CountOp(Opcode::kUnreachable), fallback ? 1u : 0u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, NestedConstantAdditions) {
  // a[(i+1)+1]; a[i+2]; a[(i+3)-1]; as produced for instance by loop
  // unrolling: all three indices are i+2.
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    V<Word32> j = __ Word32Add(i, __ Word32Constant(1));
    BoundsCheck(Asm, a, j, 1);
    BoundsCheck(Asm, a, i, 2);
    V<Word32> k = __ Word32Sub(__ Word32Add(i, __ Word32Constant(3)),
                               __ Word32Constant(1));
    BoundsCheck(Asm, a, k, 0);
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 1u);
  ASSERT_EQ(test.CountOp(Opcode::kUnreachable), 0u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, ConstantIndexOneSidedGuard) {
  // a[0]; a[1]; a[2]; -> guarded by 2 < a.length
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    BoundsCheck(Asm, a, {}, 0);
    BoundsCheck(Asm, a, {}, 1);
    BoundsCheck(Asm, a, {}, 2);
  });
  Run(test);
  // The traps are only in the fallback code.
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 3u);
  ASSERT_EQ(test.CountOp(Opcode::kUnreachable), 1u);
  // 3 original comparisons, 1 guard, 3 in the fallback code.
  ASSERT_EQ(test.CountOp(Opcode::kComparison), 7u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, NoFallbackForSingleCheck) {
  // a[0]; a[1]; could be guarded by 1 < a.length, but this only
  // eliminates one bounds check.
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    BoundsCheck(Asm, a, {}, 0);
    BoundsCheck(Asm, a, {}, 1);
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 2u);
  ASSERT_EQ(test.CountOp(Opcode::kUnreachable), 0u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, TwoSidedGuardForTwoChecks) {
  // a[i]; a[i+1]; needs a guard checking both bounds. With a single
  // comparison, it eliminates one check, which is enough for such a
  // guard.
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    BoundsCheck(Asm, a, i, 0);
    BoundsCheck(Asm, a, i, 1);
  });
  Run(test);
  bool fallback =
      FallbackInstructionSequence::single_comparison_two_sided_guard;
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 2u);
  ASSERT_EQ(test.CountOp(Opcode::kUnreachable), fallback ? 1u : 0u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, TwoSidedGuardForTwoChecksBelow) {
  // a[i+1]; a[i];
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    BoundsCheck(Asm, a, i, 1);
    BoundsCheck(Asm, a, i, 0);
  });
  Run(test);
  bool fallback =
      FallbackInstructionSequence::single_comparison_two_sided_guard;
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 2u);
  ASSERT_EQ(test.CountOp(Opcode::kUnreachable), fallback ? 1u : 0u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest,
       NoFallbackForOneSidedGuardEliminatingOneCheck) {
  // a[i]; b[i]; b[i+1]; could be guarded by i+1 < b.length, since i
  // is known to be non-negative, but this only eliminates one check.
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    BoundsCheck(Asm, a, i, 0);
    BoundsCheck(Asm, b, i, 0);
    BoundsCheck(Asm, b, i, 1);
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 3u);
  ASSERT_EQ(test.CountOp(Opcode::kUnreachable), 0u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, TwoSidedGuardForFourChecks) {
  // a[i]; a[i+1]; a[i+2]; a[i+3];
  // -> guarded by i < a.length && i+3 < a.length, or on 64-bit targets
  // by zext(i) + 3 < zext(a.length)
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    BoundsCheck(Asm, a, i, 0);
    BoundsCheck(Asm, a, i, 1);
    BoundsCheck(Asm, a, i, 2);
    BoundsCheck(Asm, a, i, 3);
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 4u);
  ASSERT_EQ(test.CountOp(Opcode::kUnreachable), 1u);
  // 4 original comparisons, the guard, 4 in the fallback code.
  ASSERT_EQ(test.CountOp(Opcode::kComparison), 8u + kTwoSidedGuardComparisons);
  ASSERT_EQ(CountWord64Comparisons(test),
            FallbackInstructionSequence::single_comparison_two_sided_guard);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, TwoSidedGuardForThreeChecks) {
  // a[i]; a[i+1]; a[i+2];
  // With a single comparison for the guard, it eliminates two checks.
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    BoundsCheck(Asm, a, i, 0);
    BoundsCheck(Asm, a, i, 1);
    BoundsCheck(Asm, a, i, 2);
  });
  Run(test);
  bool fallback =
      FallbackInstructionSequence::single_comparison_two_sided_guard;
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 3u);
  ASSERT_EQ(test.CountOp(Opcode::kUnreachable), fallback ? 1u : 0u);
  ASSERT_EQ(CountWord64Comparisons(test), fallback ? 1u : 0u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, TwoSidedGuardForChainBelow) {
  // a[i+7]; a[i+5]; a[i+3]; a[i+1];
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    BoundsCheck(Asm, a, i, 7);
    BoundsCheck(Asm, a, i, 5);
    BoundsCheck(Asm, a, i, 3);
    BoundsCheck(Asm, a, i, 1);
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 4u);
  ASSERT_EQ(test.CountOp(Opcode::kUnreachable), 1u);
  ASSERT_EQ(test.CountOp(Opcode::kComparison), 8u + kTwoSidedGuardComparisons);
}

TEST_F(WasmBoundsCheckEliminationReducerTest,
       NonNegativeIndexMakesCheckRedundant) {
  // a[i]; b[i+1]; b[i];
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    BoundsCheck(Asm, a, i, 0);
    BoundsCheck(Asm, b, i, 1);
    BoundsCheck(Asm, b, i, 0);
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 2u);
  ASSERT_EQ(test.CountOp(Opcode::kUnreachable), 0u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, NonNegativeIndexLearntLater) {
  // b[i+5]; a[i]; b[i+1];
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    BoundsCheck(Asm, b, i, 5);
    BoundsCheck(Asm, a, i, 0);
    BoundsCheck(Asm, b, i, 1);
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 2u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest,
       NonNegativeIndexDoesNotCoverSmallerOffsets) {
  // a[i+2]; b[i+1]; b[i];
  // On 64-bit targets, b[i+1]; b[i]; also get fallback code.
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    BoundsCheck(Asm, a, i, 2);
    BoundsCheck(Asm, b, i, 1);
    BoundsCheck(Asm, b, i, 0);
  });
  Run(test);
  bool fallback =
      FallbackInstructionSequence::single_comparison_two_sided_guard;
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 3u);
  ASSERT_EQ(test.CountOp(Opcode::kUnreachable), fallback ? 1u : 0u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, NonNegativeIndexOneSidedGuard) {
  // a[i]; b[i]; b[i+1]; b[i+2]; -> guarded by i+2 < b.length
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    BoundsCheck(Asm, a, i, 0);
    BoundsCheck(Asm, b, i, 0);
    BoundsCheck(Asm, b, i, 1);
    BoundsCheck(Asm, b, i, 2);
  });
  Run(test);
  // The first trap, and the other three in the fallback code.
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 4u);
  ASSERT_EQ(test.CountOp(Opcode::kUnreachable), 1u);
  // 4 original comparisons, 1 guard, 3 in the fallback code.
  ASSERT_EQ(test.CountOp(Opcode::kComparison), 8u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest,
       NonNegativeIndexFromSignedComparison) {
  // if (i >= 0) { a[i+1]; a[i]; }
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    If(Asm, __ Int32LessThanOrEqual(__ Word32Constant(0), i), [&]() {
      BoundsCheck(Asm, a, i, 1);
      BoundsCheck(Asm, a, i, 0);
    });
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 1u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest,
       NonNegativeIndexFromUnsignedComparison) {
  // if (i < 100) { a[i+1]; a[i]; }
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    If(Asm, __ Uint32LessThan(i, __ Word32Constant(100)), [&]() {
      BoundsCheck(Asm, a, i, 1);
      BoundsCheck(Asm, a, i, 0);
    });
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 1u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest,
       NoNonNegativeIndexFromLargeBound) {
  // if (i < 0x80000001) { a[i+1]; a[i]; }
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    If(Asm, __ Uint32LessThan(i, __ Word32Constant(0x80000001)), [&]() {
      BoundsCheck(Asm, a, i, 1);
      BoundsCheck(Asm, a, i, 0);
    });
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 2u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, NoFactsFromNonDominatingBranch) {
  // if (c) { a[i]; } a[i];
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    If(Asm, c, [&]() { BoundsCheck(Asm, a, i, 0); });
    BoundsCheck(Asm, a, i, 0);
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 2u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, FactsFromDominatingBranch) {
  // if (i < a.length) { a[i]; }
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    V<Word32> length = __ ArrayLength(a, compiler::kWithNullCheck);
    If(Asm, __ Uint32LessThan(i, length), [&]() { BoundsCheck(Asm, a, i, 0); });
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 0u);
}

// b[i] shows that i is non-negative. Then a[i+5]; a[i+6]; a[i+7] and
// a[i-1]; a[i-2]; a[i-3] give two fallback sequences with a one-sided
// guard each. The condition of a[i-1] is computed right after the trap
// of a[i+7] when {gap} is false, and one instruction later otherwise.
template <typename Asm_t>
static void TwoSequences(Asm_t& Asm, V<WasmArrayNullable> a,
                         V<WasmArrayNullable> b, V<Word32> i, bool gap) {
  using Test = WasmBoundsCheckEliminationReducerTest;
  Test::BoundsCheck(Asm, b, i, 0);
  Test::BoundsCheck(Asm, a, i, 5);
  Test::BoundsCheck(Asm, a, i, 6);
  V<Word32> length = __ ArrayLength(a, compiler::kWithNullCheck);
  V<Word32> index = __ Word32Add(i, __ Word32Constant(-1));
  Test::BoundsCheck(Asm, a, i, 7);
  if (gap) __ Word32Add(i, __ Word32Constant(42));
  __ TrapIfNot(__ Uint32LessThan(index, length), TrapId::kTrapArrayOutOfBounds);
  Test::BoundsCheck(Asm, a, i, -2);
  Test::BoundsCheck(Asm, a, i, -3);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, CoalesceTouchingSequences) {
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    TwoSequences(Asm, a, b, i, /*gap*/ false);
  });
  Run(test);
  // A single fallback sequence, with a two-sided guard, covers the
  // six bounds checks of {a}.
  ASSERT_EQ(test.CountOp(Opcode::kUnreachable), 1u);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 7u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, NoCoalescingAcrossGap) {
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    TwoSequences(Asm, a, b, i, /*gap*/ true);
  });
  Run(test);
  // The two sequences do not overlap, so they are kept separate.
  ASSERT_EQ(test.CountOp(Opcode::kUnreachable), 2u);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 7u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, FallbackSequenceStartingAtTrap) {
  // a[i]; b[i]; b[i+1]; b[i+2]; where the condition of the check of b[i]
  // is not right before its trap, so the fallback code starts at the
  // trap.
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    BoundsCheck(Asm, a, i, 0);
    V<Word32> length = __ ArrayLength(b, compiler::kWithNullCheck);
    V<Word32> condition = __ Uint32LessThan(i, length);
    __ Word32Add(i, __ Word32Constant(42));
    __ TrapIfNot(condition, TrapId::kTrapArrayOutOfBounds);
    BoundsCheck(Asm, b, i, 1);
    BoundsCheck(Asm, b, i, 2);
  });
  Run(test);
  // The first trap, and the other three in the fallback code.
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 4u);
  ASSERT_EQ(test.CountOp(Opcode::kUnreachable), 1u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, OCamlBoundsCheck) {
  // a[0]; if (a.length - 1 <= i) fail; a[i+1];
  // The first access shows that the length is at least 1, so the OCaml
  // bounds check shows that a[i+1] is within bounds.
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    BoundsCheck(Asm, a, {}, 0);
    FailIf(Asm, __ Uint32LessThanOrEqual(ReducedLength(Asm, a, 1), i));
    BoundsCheck(Asm, a, i, 1);
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 1u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, OCamlBoundsCheckAsAddition) {
  // a[0]; if (a.length + (-1) <= i) fail; a[i+1];
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    BoundsCheck(Asm, a, {}, 0);
    V<Word32> length = __ ArrayLength(a, compiler::kWithNullCheck);
    FailIf(Asm, __ Uint32LessThanOrEqual(
                    __ Word32Add(length, __ Word32Constant(-1)), i));
    BoundsCheck(Asm, a, i, 1);
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 1u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, OrOfConditions) {
  // if ((a.length <= i) | (b.length <= i)) fail; a[i]; b[i];
  // When the or does not hold, neither condition holds.
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    V<Word32> a_length = __ ArrayLength(a, compiler::kWithNullCheck);
    V<Word32> b_length = __ ArrayLength(b, compiler::kWithNullCheck);
    FailIf(Asm, __ Word32BitwiseOr(__ Uint32LessThanOrEqual(a_length, i),
                                   __ Uint32LessThanOrEqual(b_length, i)));
    BoundsCheck(Asm, a, i, 0);
    BoundsCheck(Asm, b, i, 0);
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 0u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, OrOfConditionsHolding) {
  // if ((i < a.length) | c) a[i];
  // The or holding does not show that one of its conditions holds.
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    V<Word32> a_length = __ ArrayLength(a, compiler::kWithNullCheck);
    If(Asm, __ Word32BitwiseOr(__ Uint32LessThan(i, a_length), c),
       [&] { BoundsCheck(Asm, a, i, 0); });
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 1u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, OrOfConditionsHoldingNegated) {
  // if ((a.length <= i) | c) a[i];
  // The or holding does not show that its conditions do not hold.
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    V<Word32> a_length = __ ArrayLength(a, compiler::kWithNullCheck);
    If(Asm, __ Word32BitwiseOr(__ Uint32LessThanOrEqual(a_length, i), c),
       [&] { BoundsCheck(Asm, a, i, 0); });
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 1u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, AndOfConditions) {
  // if ((i < a.length) & (i < b.length)) { a[i]; b[i]; }
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    V<Word32> a_length = __ ArrayLength(a, compiler::kWithNullCheck);
    V<Word32> b_length = __ ArrayLength(b, compiler::kWithNullCheck);
    If(Asm,
       __ Word32BitwiseAnd(__ Uint32LessThan(i, a_length),
                           __ Uint32LessThan(i, b_length)),
       [&] {
         BoundsCheck(Asm, a, i, 0);
         BoundsCheck(Asm, b, i, 0);
       });
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 0u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, AndOfValues) {
  // if ((i < a.length) & c) a[i];
  // {c} is not a comparison, so the and may not hold when it is not 0:
  // (1 & 2) is 0, for instance. Nothing is learnt.
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    V<Word32> a_length = __ ArrayLength(a, compiler::kWithNullCheck);
    If(Asm, __ Word32BitwiseAnd(__ Uint32LessThan(i, a_length), c),
       [&] { BoundsCheck(Asm, a, i, 0); });
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 1u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, NegatedCondition) {
  // if ((i < a.length) == 0) fail; a[i];
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    V<Word32> a_length = __ ArrayLength(a, compiler::kWithNullCheck);
    FailIf(Asm, __ Word32Equal(__ Uint32LessThan(i, a_length), 0));
    BoundsCheck(Asm, a, i, 0);
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 0u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, SignedComparison) {
  // b[i]; if (a.length - 2 <=s i) fail; a[i]; a[i+1]; a[i+2];
  // b[i] shows that i is non-negative, so the signed comparison shows
  // that i + 2 < a.length, without knowing the length of a.
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    BoundsCheck(Asm, b, i, 0);
    FailIf(Asm, __ Int32LessThanOrEqual(ReducedLength(Asm, a, 2), i));
    BoundsCheck(Asm, a, i, 0);
    BoundsCheck(Asm, a, i, 1);
    BoundsCheck(Asm, a, i, 2);
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 1u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, SignedComparisonWithUnknownSign) {
  // if (a.length - 2 <=s i) fail; a[i];
  // i may be negative.
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    FailIf(Asm, __ Int32LessThanOrEqual(ReducedLength(Asm, a, 2), i));
    BoundsCheck(Asm, a, i, 0);
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 1u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest,
       SignedComparisonAboveCheckedOffset) {
  // a[i]; if (!(i + 5 <s a.length)) fail; a[i+5];
  // i + 5 is non-negative, since i is within bounds and array lengths
  // are small.
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    BoundsCheck(Asm, a, i, 0);
    V<Word32> a_length = __ ArrayLength(a, compiler::kWithNullCheck);
    FailIf(Asm, __ Int32LessThanOrEqual(a_length,
                                        __ Word32Add(i, __ Word32Constant(5))));
    BoundsCheck(Asm, a, i, 5);
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 1u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, SignedLessThanOrEqual) {
  // b[i]; if (i <=s a.length - 2) a[i+2];
  // i + 2 may be the length of a.
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    BoundsCheck(Asm, b, i, 0);
    If(Asm, __ Int32LessThanOrEqual(i, ReducedLength(Asm, a, 2)),
       [&] { BoundsCheck(Asm, a, i, 2); });
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 2u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest,
       SignedComparisonFarAboveCheckedOffset) {
  // a[i]; if (!(i + 0x7fffffff <s a.length)) fail; a[i+0x7fffffff];
  // i + 0x7fffffff may be negative.
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    BoundsCheck(Asm, a, i, 0);
    V<Word32> a_length = __ ArrayLength(a, compiler::kWithNullCheck);
    FailIf(Asm, __ Int32LessThanOrEqual(
                    a_length, __ Word32Add(i, __ Word32Constant(0x7fffffff))));
    BoundsCheck(Asm, a, i, 0x7fffffff);
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 2u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, SignedComparisonMinLength) {
  // b[i]; if (a.length - 1 <=s i) fail; if (a.length - 3 <= c) fail;
  // a[c+3];
  // The signed comparison shows that the length of a is at least 2, not
  // 3: a.length - 3 may wrap around, and a[c+3] may be out of bounds.
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    BoundsCheck(Asm, b, i, 0);
    FailIf(Asm, __ Int32LessThanOrEqual(ReducedLength(Asm, a, 1), i));
    FailIf(Asm, __ Uint32LessThanOrEqual(ReducedLength(Asm, a, 3), c));
    BoundsCheck(Asm, a, c, 3);
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 2u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, OCamlBoundsCheckUnknownLength) {
  // if (a.length - 1 <= i) fail; a[i+1];
  // The array might be empty, in which case a.length - 1 wraps around
  // and the OCaml bounds check does not show anything.
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    FailIf(Asm, __ Uint32LessThanOrEqual(ReducedLength(Asm, a, 1), i));
    BoundsCheck(Asm, a, i, 1);
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 1u);
}

// The sign extension of a 31-bit integer, as done by wasm_of_ocaml.
template <typename Asm_t>
static V<Word32> SignExtend31(Asm_t& Asm, V<Word32> value, int shift = 1) {
  return __ Word32ShiftRightArithmetic(
      __ Word32ShiftLeft(value, __ Word32Constant(shift)),
      __ Word32Constant(shift));
}

TEST_F(WasmBoundsCheckEliminationReducerTest, DuplicatedComputations) {
  // a[0]; if (a.length - 1 <= sext(i - c)) fail; a[sext(i - c) + 1];
  // where {sext(i - c)} is computed twice. Both computations have the
  // same value, so the OCaml bounds check covers the Wasm one.
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    BoundsCheck(Asm, a, {}, 0);
    FailIf(Asm,
           __ Uint32LessThanOrEqual(ReducedLength(Asm, a, 1),
                                    SignExtend31(Asm, __ Word32Sub(i, c))));
    BoundsCheck(Asm, a, SignExtend31(Asm, __ Word32Sub(i, c)), 1);
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 1u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, DifferentComputations) {
  // a[0]; if (a.length - 1 <= sext(i)) fail; a[sext2(i) + 1];
  // where {sext2} shifts by 2 instead of 1: the values differ.
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    BoundsCheck(Asm, a, {}, 0);
    FailIf(Asm, __ Uint32LessThanOrEqual(ReducedLength(Asm, a, 1),
                                         SignExtend31(Asm, i)));
    BoundsCheck(Asm, a, SignExtend31(Asm, i, 2), 1);
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 2u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, OCamlBoundsChecksInSequence) {
  // a[i+1] after the OCaml bounds check of a.(i) shows that the length is
  // at least 1, so the Wasm bounds checks of a.(j) and a.(k) are
  // redundant.
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    FailIf(Asm, __ Uint32LessThanOrEqual(ReducedLength(Asm, a, 1), i));
    BoundsCheck(Asm, a, i, 1);
    FailIf(Asm, __ Uint32LessThanOrEqual(ReducedLength(Asm, a, 1), c));
    BoundsCheck(Asm, a, c, 1);
    V<Word32> k = __ Word32Add(i, c);
    FailIf(Asm, __ Uint32LessThanOrEqual(ReducedLength(Asm, a, 1), k));
    BoundsCheck(Asm, a, k, 1);
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 1u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, ReducedLengthCoversRange) {
  // a[1]; if (i < a.length - 2) { a[i]; a[i+1]; a[i+2]; }
  // a[1] shows that the length is at least 2.
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    BoundsCheck(Asm, a, {}, 1);
    If(Asm, __ Uint32LessThan(i, ReducedLength(Asm, a, 2)), [&]() {
      BoundsCheck(Asm, a, i, 0);
      BoundsCheck(Asm, a, i, 1);
      BoundsCheck(Asm, a, i, 2);
    });
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 1u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, ReducedLengthTooLarge) {
  // a[0]; if (i < a.length - 2) { a[i+2]; }
  // a[0] only shows that the length is at least 1, so a.length - 2 may
  // wrap around.
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    BoundsCheck(Asm, a, {}, 0);
    If(Asm, __ Uint32LessThan(i, ReducedLength(Asm, a, 2)),
       [&]() { BoundsCheck(Asm, a, i, 2); });
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 2u);
}

// Loops over {k}, starting at {init} and adding {step}, with {exit}
// testing whether to leave the loop before {body}, and after {before}.
template <typename Asm_t, typename Exit, typename Body,
          typename Before = void (*)(V<Word32>)>
static void Loop(
    Asm_t& Asm, int32_t init, int32_t step, const Exit& exit, const Body& body,
    const Before& before = [](V<Word32>) {}) {
  LoopLabel<Word32> loop(&Asm);
  Label<> done(&Asm);
  GOTO(loop, __ Word32Constant(init));
  BIND_LOOP(loop, k) {
    before(k);
    GOTO_IF(exit(k), done);
    body(k);
    GOTO(loop, __ Word32Add(k, __ Word32Constant(step)));
  }
  BIND(done);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, LoopWithSignedBound) {
  // for (k = 0; k <s a.length - 2; k += 3) { a[k]; a[k+1]; a[k+2]; }
  // k is non-negative, since it starts at 0, and its increments cannot
  // overflow, so the signed comparison covers the three accesses.
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    Loop(
        Asm, 0, 3,
        [&](V<Word32> k) {
          return __ Int32LessThanOrEqual(ReducedLength(Asm, a, 2), k);
        },
        [&](V<Word32> k) {
          BoundsCheck(Asm, a, k, 0);
          BoundsCheck(Asm, a, k, 1);
          BoundsCheck(Asm, a, k, 2);
        });
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 0u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, LoopWithNegativeStart) {
  // for (k = -1; k <s a.length - 1; k += 1) { a[k+1]; a[k]; }
  // k may be negative.
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    Loop(
        Asm, -1, 1,
        [&](V<Word32> k) {
          return __ Int32LessThanOrEqual(ReducedLength(Asm, a, 1), k);
        },
        [&](V<Word32> k) {
          BoundsCheck(Asm, a, k, 1);
          BoundsCheck(Asm, a, k, 0);
        });
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 2u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, LoopWithNegativeStep) {
  // for (k = 0; k <s a.length - 1; k -= 1) { a[k+1]; a[k]; }
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    Loop(
        Asm, 0, -1,
        [&](V<Word32> k) {
          return __ Int32LessThanOrEqual(ReducedLength(Asm, a, 1), k);
        },
        [&](V<Word32> k) {
          BoundsCheck(Asm, a, k, 1);
          BoundsCheck(Asm, a, k, 0);
        });
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 2u);
}

template <typename Asm_t>
static void LoopWithConstantBound(Asm_t& Asm, V<WasmArrayNullable> a,
                                  int32_t bound, bool is_signed = true) {
  // for (k = 0; ; k += 3) {
  //   if (!(a.length - 1 <=s k)) { a[k+1]; a[k]; }
  //   if (!(k < bound)) break;
  // }
  // The accesses come before the exit test, so that only the induction
  // shows that k is non-negative.
  using Test = WasmBoundsCheckEliminationReducerTest;
  Loop(
      Asm, 0, 3,
      [&](V<Word32> k) {
        return is_signed ? __ Int32LessThanOrEqual(__ Word32Constant(bound), k)
                         : __ Uint32LessThanOrEqual(__ Word32Constant(bound),
                                                    k);
      },
      [&](V<Word32> k) {},
      [&](V<Word32> k) {
        Label<> next(&Asm);
        GOTO_IF(__ Int32LessThanOrEqual(Test::ReducedLength(Asm, a, 1), k),
                next);
        Test::BoundsCheck(Asm, a, k, 1);
        Test::BoundsCheck(Asm, a, k, 0);
        GOTO(next);
        BIND(next);
      });
}

TEST_F(WasmBoundsCheckEliminationReducerTest, LoopWithSmallConstantBound) {
  // With k < 0x7ffffffd, k + 3 cannot overflow.
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    LoopWithConstantBound(Asm, a, 0x7ffffffd);
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 0u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest,
       LoopWithSmallUnsignedConstantBound) {
  // With k <u 0x7ffffffd, k + 3 cannot overflow.
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    LoopWithConstantBound(Asm, a, 0x7ffffffd, false);
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 0u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest,
       LoopWithLargeUnsignedConstantBound) {
  // With k <u 0x7ffffffe, k + 3 may overflow (as a signed integer).
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    LoopWithConstantBound(Asm, a, 0x7ffffffe, false);
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 2u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, LoopWithLargeConstantBound) {
  // With k < 0x7ffffffe, k + 3 may overflow.
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    LoopWithConstantBound(Asm, a, 0x7ffffffe);
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 2u);
}

// for (k = init; k != hi; k++) body, where the loop is only entered if
// {guard} holds.
template <typename Asm_t, typename Guard, typename Body>
static void NotEqualLoop(Asm_t& Asm, V<Word32> hi, int32_t init, int32_t step,
                         const Guard& guard, const Body& body) {
  Label<> done(&Asm);
  GOTO_IF_NOT(guard(), done);
  LoopLabel<Word32> loop(&Asm);
  GOTO(loop, __ Word32Constant(init));
  BIND_LOOP(loop, k) {
    body(k);
    for (int32_t n = 0; n < step; n++) {
      GOTO_IF(__ Word32Equal(__ Word32Add(k, __ Word32Constant(n)), hi), done);
    }
    GOTO(loop, __ Word32Add(k, __ Word32Constant(step)));
  }
  BIND(done);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, NotEqualLoop) {
  // hi = a.length - 1; if (0 <= hi) for (k = 0; ; k++) {
  //   a[k]; if (k == hi) break;
  // }
  // As for an OCaml loop {for k = 0 to Array.length a - 1}: k is at
  // most hi in the loop.
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    V<Word32> hi = ReducedLength(Asm, a, 1);
    NotEqualLoop(
        Asm, hi, 0, 1,
        [&] { return __ Int32LessThanOrEqual(__ Word32Constant(0), hi); },
        [&](V<Word32> k) { BoundsCheck(Asm, a, k, 0); });
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 0u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, NotEqualLoopWithoutGuard) {
  // Without the guard, k may start above hi, and go past it.
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    V<Word32> hi = ReducedLength(Asm, a, 1);
    NotEqualLoop(
        Asm, hi, 0, 1, [&] { return c; },
        [&](V<Word32> k) { BoundsCheck(Asm, a, k, 0); });
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 1u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, NotEqualLoopAboveGuard) {
  // if (0 <= hi) for (k = 1; ; k++): k may start above hi.
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    V<Word32> hi = ReducedLength(Asm, a, 1);
    NotEqualLoop(
        Asm, hi, 1, 1,
        [&] { return __ Int32LessThanOrEqual(__ Word32Constant(0), hi); },
        [&](V<Word32> k) { BoundsCheck(Asm, a, k, 0); });
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 1u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, NotEqualLoopExcludedValue) {
  // if (0 <= hi && hi != 0) for (k = 1; ; k++), as after peeling the
  // first iteration of a loop from 0: k starts at most at hi.
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    V<Word32> hi = ReducedLength(Asm, a, 1);
    Label<> done(&Asm);
    GOTO_IF(__ Int32LessThan(hi, __ Word32Constant(0)), done);
    NotEqualLoop(
        Asm, hi, 1, 1, [&] { return hi; },
        [&](V<Word32> k) { BoundsCheck(Asm, a, k, 0); });
    GOTO(done);
    BIND(done);
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 0u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, NotEqualLoopAboveExcludedValue) {
  // if (0 <= hi && hi != 0) for (k = 2; ; k++): hi may be 1.
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    V<Word32> hi = ReducedLength(Asm, a, 1);
    Label<> done(&Asm);
    GOTO_IF(__ Int32LessThan(hi, __ Word32Constant(0)), done);
    NotEqualLoop(
        Asm, hi, 2, 1, [&] { return hi; },
        [&](V<Word32> k) { BoundsCheck(Asm, a, k, 0); });
    GOTO(done);
    BIND(done);
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 1u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, NotEqualLoopWhenZero) {
  // if (0 <= hi && !hi) for (k = 1; ; k++): k starts above hi.
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    V<Word32> hi = ReducedLength(Asm, a, 1);
    Label<> done(&Asm);
    GOTO_IF(__ Int32LessThan(hi, __ Word32Constant(0)), done);
    // The loop is entered on the false edge of a branch on hi.
    GOTO_IF(hi, done);
    NotEqualLoop(
        Asm, hi, 1, 1, [&] { return c; },
        [&](V<Word32> k) { BoundsCheck(Asm, a, k, 0); });
    GOTO(done);
    BIND(done);
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 1u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, UnrolledNotEqualLoop) {
  // if (0 <= hi) for (k = 0; ; k += 2) {
  //   a[k]; if (k == hi) break; if (k + 1 == hi) break;
  // }
  // As after unrolling: k still does not go past hi.
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    V<Word32> hi = ReducedLength(Asm, a, 1);
    NotEqualLoop(
        Asm, hi, 0, 2,
        [&] { return __ Int32LessThanOrEqual(__ Word32Constant(0), hi); },
        [&](V<Word32> k) { BoundsCheck(Asm, a, k, 0); });
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 0u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, SteppingOverNotEqual) {
  // if (0 <= hi) for (k = 0; ; k += 2) { a[k]; if (k == hi) break; }
  // k may step over hi.
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    V<Word32> hi = ReducedLength(Asm, a, 1);
    Label<> done(&Asm);
    GOTO_IF_NOT(__ Int32LessThanOrEqual(__ Word32Constant(0), hi), done);
    Loop(
        Asm, 0, 2, [&](V<Word32> k) { return __ Word32Constant(0); },
        [&](V<Word32> k) {
          BoundsCheck(Asm, a, k, 0);
          GOTO_IF(__ Word32Equal(k, hi), done);
        });
    GOTO(done);
    BIND(done);
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 1u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, NotEqualToLength) {
  // a[i]; if (i + 1 == a.length) fail; a[i+1];
  // i + 1 is at most the length, and not equal to it.
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    BoundsCheck(Asm, a, i, 0);
    V<Word32> length = __ ArrayLength(a, compiler::kWithNullCheck);
    FailIf(Asm, __ Word32Equal(__ Word32Add(i, __ Word32Constant(1)), length));
    BoundsCheck(Asm, a, i, 1);
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 1u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, EqualToLength) {
  // a[i]; if (i + 1 == a.length) a[i+1];
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    BoundsCheck(Asm, a, i, 0);
    V<Word32> length = __ ArrayLength(a, compiler::kWithNullCheck);
    If(Asm, __ Word32Equal(__ Word32Add(i, __ Word32Constant(1)), length),
       [&] { BoundsCheck(Asm, a, i, 1); });
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 2u);
}

TEST_F(WasmBoundsCheckEliminationReducerTest, NotEqualToLengthTooFar) {
  // a[i]; if (i + 2 == a.length) fail; a[i+1];
  auto test = CreateTest([](auto& Asm, auto a, auto b, auto i, auto c) {
    BoundsCheck(Asm, a, i, 0);
    V<Word32> length = __ ArrayLength(a, compiler::kWithNullCheck);
    FailIf(Asm, __ Word32Equal(__ Word32Add(i, __ Word32Constant(2)), length));
    BoundsCheck(Asm, a, i, 1);
  });
  Run(test);
  ASSERT_EQ(test.CountOp(Opcode::kTrapIf), 2u);
}

#include "src/compiler/turboshaft/undef-assembler-macros.inc"

}  // namespace v8::internal::compiler::turboshaft
